name: circuit_check_app
description: "A PCB Design Analysis Tool"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  # Allows for selecting files from the file system
  file_picker: ^9.0.0
  # The Flutter SDK
  flutter:
    sdk: flutter
  # Allows files to be dragged and dropped into the Flutter app
  flutter_dropzone: ^4.2.1
  # Used to define localizable strings
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint rules for Dart and Flutter used internally at Very Good Ventures.
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
